package app

import (
	"os"

	_ "github.com/anilkusc/flow-diet-backend/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger"
)

func (app *App) InitRoutes() {
	app.Router.HandleFunc("/user/signin", app.SigninHandler).Methods("POST")
	app.Router.HandleFunc("/user/signup", app.SignupHandler).Methods("POST")
	//api.Router.HandleFunc("/user/{id}/read", IdControl(api.ReadUserHandler)).Methods("GET")
	//api.Router.HandleFunc("/user/{id}/update", IdControl(api.UpdateUserHandler)).Methods("PATCH")
	//api.Router.HandleFunc("/user/{id}/delete", IdControl(api.DeleteUserHandler)).Methods("DELETE")
	if os.Getenv("ENV") != "prod" {
		app.Router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	}
}
