basePath: /
host: localhost:8080
info:
  contact:
    email: soberkoder@swagger.io
    name: API Support
  description: This is a sample serice for managing orders
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Flow-Diet-Backend API
  version: "1.0"
paths:
  /user/{id}/create:
    get:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: Create User With Id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create a new user
      tags:
      - users
swagger: "2.0"
