package api

import (
	"os"

	_ "github.com/anilkusc/flow-diet-backend/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Api struct {
	Router *mux.Router
}

func (api *Api) InitRoutes() {
	api.Router.HandleFunc("/user/create", api.CreateUserHandler)
	api.Router.HandleFunc("/user/{id}/read", IdControl(api.ReadUserHandler))
	api.Router.HandleFunc("/user/{id}/update", IdControl(api.UpdateUserHandler))
	api.Router.HandleFunc("/user/{id}/delete", IdControl(api.DeleteUserHandler))
	if os.Getenv("ENV") != "prod" {
		api.Router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	}
}
