package api

import (
	"os"

	_ "github.com/anilkusc/flow-diet-backend/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/gorilla/mux"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Api struct {
	Router *mux.Router
}

func (api *Api) InitRoutes() {
	api.Router.HandleFunc("/user/login", api.CreateUserHandler).Methods("POST")
	api.Router.HandleFunc("/user/logout", api.CreateUserHandler).Methods("POST")
	api.Router.HandleFunc("/user/register", api.CreateUserHandler).Methods("POST")
	api.Router.HandleFunc("/user/create", api.CreateUserHandler).Methods("POST")
	//api.Router.HandleFunc("/user/{id}/read", IdControl(api.ReadUserHandler)).Methods("GET")
	//api.Router.HandleFunc("/user/{id}/update", IdControl(api.UpdateUserHandler)).Methods("PATCH")
	//api.Router.HandleFunc("/user/{id}/delete", IdControl(api.DeleteUserHandler)).Methods("DELETE")
	if os.Getenv("ENV") != "prod" {
		api.Router.PathPrefix("/swagger").Handler(httpSwagger.WrapHandler)
	}
}
